services:
  - type: web
    name: structura-backend
    env: python
    plan: free
    rootDir: backend/structura_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn structura_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: structura_backend.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://martyscrackling.github.io/aestra_structura/
