services:
  - type: web
    name: structura-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn structura_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: structura_backend.settings
      - key: PYTHONUNBUFFERED
        value: "1"
